on:
    workflow_dispatch:
        inputs:
            flutter_version:
                description: "Flutter Version"
                required: true
                type: string

jobs:
    add_flutter_app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Generate Project
              run: npm run new 3.0.5
