on:
    push:
        branches: [dev]
    workflow_dispatch:
        inputs:
            flutter_version:
                description: "Flutter Version"
                required: true
                type: string

jobs:
    add_flutter_app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.PAT }}
            # - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
            - run: curl -fsSL https://fvm.app/install.sh | bash
            - name: Git Config
              run: |
                  git config --global user.name 'Albin'
                  git config --global user.email '56157868+albinpk@users.noreply.github.com'
            - name: Generate Project
              run: npm run new ${{ inputs.flutter_version }}
            - name: Commit & Push
              run: |
                  git commit -am "From action"
                  git push
